#!/usr/bin/sh

if git rev-parse --verify HEAD >/dev/null 2>&1
then
	against=HEAD
else
	against=$(git hash-object -t tree /dev/null)
fi

exec 1>&2

if [ "$allownonascii" != "true" ] &&
	test $(git diff --cached --name-only --diff-filter=A -z $against |
	  LC_ALL=C tr -d '[ -~]\0' | wc -c) != 0
then
	cat <<\EOF
Error: Attempt to add a non-ASCII file name.

This can cause problems if you want to work with people on other platforms.

To be portable it is advisable to rename the file.

If you know what you are doing you can disable this check using:

  git config hooks.allownonascii true
EOF
	exit 1
fi

# mypart
if ansible-playbook --syntax-check -i 'localhost,' *.yml
then
  echo ansible-playbook --syntax-check succesfully!
else
  exit 1
fi

if  yamllint  -c ~/myconfig * 
then
  echo yamllint succesfully! 
else
  exit 1
fi

ansible-lint *.yml

# If there are whitespace errors, print the offending file names and fail.
exec git diff-index --check --cached $against --
